# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b0ee924bd5a4359401a42bcb7c42f03d6bcc4a9e72ceefbb7e6643a2483630b65cccfdb5fdebc24fd3f93e888f8ba40a1cfd7f0b23a46fc751fdb38e5a8c547

test:
  secret_key_base: 65ab9458a6b386680fc619767c5cf6a5be3352e76df247f3d07be26a27feedf930c44db54464e5b335f97b6da3d9d0b785e6bbd3219c88cfd736df2e3af0db4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
